import express from "express";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import User from "../models/User.js";
import {protect} from "../middleware/authMiddleware.js";
import {asyncHandler} from "../utils/asyncHandler.js";
const router=express.Router();
const tokenFor=user=>jwt.sign({id:user._id.toString(),role:user.role},process.env.JWT_SECRET,{expiresIn:"1d"});
router.post("/register",asyncHandler(async(req,res)=>{const{name,email,password}=req.body;if(!name||!email||!password)return res.status(400).json({success:false,message:"Name, email and password are required."});if(password.length<6)return res.status(400).json({success:false,message:"Password must contain at least 6 characters."});const e=email.trim().toLowerCase();if(await User.findOne({email:e}))return res.status(409).json({success:false,message:"An account with this email already exists."});const user=await User.create({name:name.trim(),email:e,passwordHash:await bcrypt.hash(password,12),role:"admin"});res.status(201).json({success:true,message:"Account created successfully.",user:{id:user._id,name:user.name,email:user.email,role:user.role}});}));
router.post("/login",asyncHandler(async(req,res)=>{const{email,password}=req.body;if(!email||!password)return res.status(400).json({success:false,message:"Email and password are required."});const user=await User.findOne({email:email.trim().toLowerCase()});if(!user||!(await bcrypt.compare(password,user.passwordHash)))return res.status(401).json({success:false,message:"Invalid email or password."});res.json({success:true,message:"Login successful.",token:tokenFor(user),user:{id:user._id,name:user.name,email:user.email,role:user.role}});}));
router.get("/me",protect,asyncHandler(async(req,res)=>{const user=await User.findById(req.user.id).select("-passwordHash");if(!user)return res.status(404).json({success:false,message:"User not found."});res.json({success:true,user});}));
export default router;
